# MySQL Database Connection configuration
db.url=jdbc:mysql://localhost:3306/foodshare?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.username=root
db.password=*!akriti434293*!
db.driver=com.mysql.cj.jdbc.Driver
